{
 "title": "streamer-template-dashboard",
 "description": "A simple dashboard to look at the streamer templates performance",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Route Task Metrics",
   "type": "timeseries",
   "description": "Examine the poll counts and delays of the API routing task",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "total_fast_poll_count{task=\"api_routing\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_slow_poll_count{task=\"api_routing\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_long_delay_count{task=\"api_routing\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_short_delay_count{task=\"api_routing\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idled_count{task=\"api_routing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Task Metrics",
   "type": "timeseries",
   "description": "Examine the poll counts and delays of the inference task",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "total_fast_poll_count{task=\"inference\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_slow_poll_count{task=\"inference\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_long_delay_count{task=\"inference\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_short_delay_count{task=\"inference\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idled_count{task=\"inference\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Audio Decoding Task Metrics",
   "type": "timeseries",
   "description": "Examine the poll counts and delays of the audio decoding task",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "total_fast_poll_count{task=\"audio_decoding\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_slow_poll_count{task=\"audio_decoding\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_long_delay_count{task=\"audio_decoding\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_short_delay_count{task=\"audio_decoding\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idled_count{task=\"audio_decoding\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Task Metrics",
   "type": "timeseries",
   "description": "Examine the poll counts and delays of the client responding task",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "total_fast_poll_count{task=\"client\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_slow_poll_count{task=\"client\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_long_delay_count{task=\"client\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "total_short_delay_count{task=\"client\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "idled_count{task=\"client\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panic Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "total_task_panic_count", "legendFormat": "__auto" }
   ]
  }
 ]
}