[package]
name = "streamer-template"
version = "0.1.0"
edition = "2021"
default-run = "streamer-template"

[features]
default = ["axum", "tokio-tungstenite"]
axum = ["dep:axum", "tokio-tungstenite"]
tokio-tungstenite = ["dep:tokio-tungstenite"]
hound = ["dep:hound"]

[dependencies]
anyhow = "1.0.82"
axum = { version = "0.7.5", optional = true, features = ["tracing", "ws"] }
bytes = "1.6.0"
clap = { version = "4.5.4", features = ["derive"] }
fastrand = "2.1.0"
futures = "0.3.30"
hound = { version = "3.5.1", optional = true }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["macros", "sync", "rt-multi-thread"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
tokio-tungstenite = { version = "0.21.0", optional = true }
tower-http = { version = "0.5.2", features = ["trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
tracing-test = "0.2.4"

[[bin]]
name = "client"
required-features = ["tokio-tungstenite", "hound"]
