[package]
name = "streamer-template"
version = "0.1.0"
edition = "2021"

[features]
default = ["actix", "axum", "tokio-tungstenite"] # Trash my build time 
actix = ["dep:actix", "actix-web", "actix-web-actors"]
axum = ["dep:axum"]
tokio-tungstenite = ["dep:tokio-tungstenite"]

[dependencies]
actix = { version = "0.13.3", optional = true }
actix-web = { version = "4.5.1", optional = true }
actix-web-actors = { version = "4.3.0", optional = true }
anyhow = "1.0.82"
axum = { version = "0.7.5", optional = true, features = ["ws"] }
bytes = "1.6.0"
fastrand = "2.1.0"
futures = "0.3.30"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["macros", "sync", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.21.0", optional = true }
tower-http = { version = "0.5.2", features = ["trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
tracing-test = "0.2.4"

[[bin]]
name = "client"
required-features = ["tokio-tungstenite"]
