version: "2.2"
services:
  streamer-template:
    image: streamer-template
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "streamer-template"
    ports:
      - "3000:3000"
  jaeger:
    image: jaegertracing/all-in-one:1.57.0
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4317:4317"
      #- "6831:6831/udp"
      #- "6832:6832/udp"
      #- "5778:5778"
      #- "4318:4318"
      #- "14250:14250"
      #- "14268:14268"
      #- "14269:14269"
      #- "9411:9411"
