version: "2.2"
services:
  streamer-template:
    image: streamer-template
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "streamer-template"
    ports:
      - "8080:8080"
# Devops supporting services!
  prometheus:
    image: prom/prometheus:v2.54.0
    ports:
      - 9090:9090
    volumes:
      - ./devops/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:11.1.2
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
        - "3000:3000"
    volumes:
      - ./devops/grafana/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - grafana-data:/var/lib/grafana
  jaeger:
    image: jaegertracing/all-in-one:1.57.0
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4317:4317"
      #- "6831:6831/udp"
      #- "6832:6832/udp"
      #- "5778:5778"
      #- "4318:4318"
      #- "14250:14250"
      #- "14268:14268"
      #- "14269:14269"
      #- "9411:9411"
volumes:
  prometheus-data:
  grafana-data:
